### PR TITLE
Refactoring of the MultiVolumeExplorer

### PR DESCRIPTION
**Pull request by che85**
- In order to be reused in other modules with a simplified version
- work in progress

### CODE REVIEW

**Comment by fedorov** [comment]
You need to list the newly added python file in Py/CMakeFiles.txt so that it is installed/packaged properly.  See https://github.com/fedorov/MultiVolumeExplorer/blob/master/Py/CMakeLists.txt#L2-L5

**Comment by che85** [comment]
ok. I will commit it

**Comment by fedorov** [comment]
Frame control dropdown looks empty in my tests:

image

**Comment by fedorov** [comment]
no errors in the python console

**Comment by che85** [comment]
Ok that's the issue I mentioned to you a few days ago. I am going to dive into that

**Comment by fedorov** [comment]
Can you also comment "processing event Mouse*Event" print? I know it is not yours! :)

**Comment by fedorov** [comment]
It is fine to put the content from Frame control into the Input panel, perhaps this will make your life easier.

**Comment by che85** [comment]
frame controls now available in inputframe

**Comment by fedorov** [comment]
now the issue is that no matter what is the size of the surrounding widgets, the chart widget size remains constant...

image

**Comment by che85** [comment]
Ok will make that more flexible

**Comment by fedorov** [comment]
Thanks a lot!

**Pull request merged**
