### PR TITLE
Update plots to new slicer plots infrastructure

### PR DESCRIPTION
**Pull request by Kmacneil0102**
Addresses #38. 

Awaiting addition of access to log scale plot setting to Slicer core.

### CODE REVIEW

**Comment by Kmacneil0102** [comment]
@che85 Everything should function correctly except for the "Use log scale for axis" plot option!

**Comment by che85** [comment]
Do you know when the log scale option will be available? But I don't think it's critical right now.

**Comment by Kmacneil0102** [comment]
@lassoan said he would add it, but i'm not sure when.

**Comment by lassoan** [comment]
It's ready. It'll be available in tomorrow's nightly build.

**Pull request merged**
