### PR TITLE
Tweak cmakelists

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @fedorov

**Comment by jcfr** [comment]
This topic will allow Slicer to be built setting CMP0048 to NEW

**Comment by fedorov** [comment]
I guess this came up while you were upgrading the factory compilers ... sorry about that!

**Comment by jcfr** [comment]
> upgrading the factory compilers

Not yet. 

This is in anticipation.

Setting policy to `OLD` is not recommended. It is important to get ride of deprecated situation.

**Comment by jcfr** [comment]
Thanks for merging.

**Pull request merged**
